### ISSUE TITLE
Symbion's test packed_elf_x64 avatar No Memory range specified at 0x400cd6

### ISSUE THREAD

**Issue by visionius** [angr/angr-targets#10]
As I issued in #8 
First I commented these three lines in /avatar2/protocols/gdb.py:
line:270
```
self._gdbmi = pygdbmi.gdbcontroller.GdbController()
#gdb_path=gdb_executable,
#gdb_args=gdb_args,
#verbose=True)
```
I used manual_concrete_packed_elf64.py file and pass the binary file that is available in angr-symbion blog. But the concrete execution is not sync to symbolic state... I don't know the changes that I have been done to that code was the reason or not, exploration can't find the symbolic path and I have avatar No memory range CRITICAL error.
ubuntu x86_64 python3.6 angr and angr-target successfully installed without problems.

shot:
 
![image](https://user-images.githubusercontent.com/34987886/104824909-77d31800-586b-11eb-9b4e-a17340340471.png)

**Comment by degrigis** [comment]
Hey there, sorry for the delay, I'll look into this ASAP!

**Comment by ringzer0x00** [comment]
I'm having the same issue, tested it with both gdb 10.1 and 8.2.1, assuming it could have been some older protocol implementations in the avatar-based scripts. Apparently it isn't.

**Comment by ringzer0x00** [comment]
Tested a bit the whole thing, as we have the same problem most likely. 
There seems to be some kind of issue on the protocol level on the reception side when it is dealing with memory-related operations.
Running avatar2 tests they fail exactly when reading the response.
Not sure about this, but apparently the commands sent are fine.

**Comment by visionius** [comment]
Install angr-dev and fresh pip tool installation tackled the issue. Thank you both @degrigis  and @ringzer0x00
