### ISSUE TITLE
 dynamically loaded library problem

### ISSUE THREAD

**Issue by XMUsuny** [angr/angr-targets#13]
Hi, I'm interested in the novel method symbion and have tested the demo. I want to use angr's symbolic execution to test a dynamic library (used by a tcp server), so I use symbion to synchronize the state after the server is initialized and dynamically load the library in the project (also add new memory backer). However, I find after synchronizion angr can not continue the execute the code in the address space of the library, showing "bytes can only be stored big-endian". Could you give me some suggestions?
Thank you.

**Comment by bspdev** [comment]
Why is this issue closed? I have the same issue with Symbion.
@XMUsuny did you fix your problem?

Thanks

**Comment by SteinsGatep001** [comment]
I have the same problem.
