### ISSUE TITLE
I received a problem when run

### ISSUE THREAD

**Issue by tower111** [angr/angr-targets#14]
➜  angr-targets git:(master) python tests/disabled_gdb_target_linux.py 
Traceback (most recent call last):
  File "tests/disabled_gdb_target_linux.py", line 5, in <module>
    from angr_targets.segment_registers import *
ModuleNotFoundError: No module named 'angr_targets.segment_registers'

I cann't find the file.

**Comment by twizmwazin** [comment]
These tests look to be disabled and unmaintained, we may want to consider removing them unless someone steps up to update them.

**Comment by degrigis** [comment]
Yeah, I'll clean the useless tests.
