### ISSUE TITLE
AvatarGDBConcreteTarget for arm

### ISSUE THREAD

**Issue by SteinsGatep001** [angr/angr-targets#23]
Trying to create a gdb concrete target using `AvatarGDBConcreteTarget(avatar2.archs.arm.ARM, 'localhost', port)`.
```Python
avatar_gdb = AvatarGDBConcreteTarget(avatar2.archs.arm.ARM, 'localhost', port)
p = angr.Project(target, concrete_target=avatar_gdb, use_sim_procedures=True)
```
But it shows that:
```Python
angr.project.CRITICAL | Concrete execution does not support yet the selected architecture. Aborting.
```
Should I add the concrete for this architecture myself or is there already another branch that supports this arch?

**Comment by degrigis** [comment]
Sorry for the late response, this sled under my radar. 
It seems that there is a mismatch between the string ID used by Avatar2 for ARM and the one we are expecting when creating a concrete target? See here https://github.com/angr/angr/blob/master/angr/project.py#L170

**Comment by SteinsGatep001** [comment]
the binary archis : Arch ARMEL (LE)

**Comment by degrigis** [comment]
Providing that you know how to synchronize the concrete state of a program running on ARMEL (the best case scenario is that under the hood is the same as `ARMHF`), you should be good with that simple modification.
