### ISSUE TITLE
no such option --process-dependency-links

### ISSUE THREAD

**Issue by bannsec** [angr/angr-targets#7]
As of pip version 19, there is no longer the option `--process-dependency-links`.

**Comment by twizmwazin** [comment]
This is default behavior now, correct? So the proper solution would be to stop using the flag, and remove it from the readme.

**Comment by bannsec** [comment]
I had just tried installing it and basically it installs without installing
the avatar2 requirement.

**Comment by twizmwazin** [comment]
@bannsec What is your `sys.platform`? https://github.com/angr/angr-targets/blob/master/setup.py#L10

**Comment by bannsec** [comment]
Ah, well that would explain that. Installed on windows.

**Comment by stevenskevin** [comment]
This isn't fixed -- the readme still suggests an installation command that no longer works. Could this issue be reopened?

**Comment by ltfish** [comment]
@twizmwazin ping

**Comment by twizmwazin** [comment]
@stevenskevin You should be able to install this using `python setup.py develop` or `pip install -e .`

**Comment by stevenskevin** [comment]
I was able to install this by temporarily downgrading pip to 18.1. I'd just like for the readme to be updated so that it doesn't recommend a broken command, is all.
